// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Reports(catNames []string, catTotals []float64, nwLabels []string, nwValues []float64) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full h-full p-4 flex flex-col gap-4\"><div class=\"grid grid-cols-1 lg:grid-cols-2 gap-4\"><!-- Spending by category (this month) --><div class=\"bg-white rounded-xl shadow-card p-5 border border-stone-100\"><h2 class=\"text-base font-semibold font-display text-stone-800 mb-4\">Spending by Category</h2><div id=\"cat-data\" data-labels=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(buildJSONArray(catNames))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/reports.templ`, Line: 10, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-values=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(buildJSONFloatArray(catTotals))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/reports.templ`, Line: 11, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"hidden\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(catNames) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p class=\"text-sm text-stone-400 text-center py-10\">No expenses this month yet</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<canvas id=\"category-chart\" height=\"200\"></canvas>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><!-- Net worth over time --><div class=\"bg-white rounded-xl shadow-card p-5 border border-stone-100\"><h2 class=\"text-base font-semibold font-display text-stone-800 mb-4\">Net Worth Trend</h2><div id=\"nw-data\" data-labels=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(buildJSONArray(nwLabels))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/reports.templ`, Line: 24, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-values=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(buildJSONFloatArray(nwValues))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/reports.templ`, Line: 25, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" class=\"hidden\"></div><canvas id=\"networth-chart\" height=\"200\"></canvas></div></div><script>\n\t\t\t(function () {\n\t\t\t\tvar cat = document.getElementById('cat-data');\n\t\t\t\tvar catCanvas = document.getElementById('category-chart');\n\t\t\t\tif (cat && catCanvas) {\n\t\t\t\t\tnew Chart(catCanvas.getContext('2d'), {\n\t\t\t\t\t\ttype: 'doughnut',\n\t\t\t\t\t\tdata: {\n\t\t\t\t\t\t\tlabels: JSON.parse(cat.dataset.labels),\n\t\t\t\t\t\t\tdatasets: [{\n\t\t\t\t\t\t\t\tdata: JSON.parse(cat.dataset.values),\n\t\t\t\t\t\t\t\tbackgroundColor: ['#b8862f','#9c6f28','#caa049','#d9b972','#7d5722','#e8d3a6','#553c1e','#66471f'],\n\t\t\t\t\t\t\t\tborderWidth: 0\n\t\t\t\t\t\t\t}]\n\t\t\t\t\t\t},\n\t\t\t\t\t\toptions: { responsive: true, plugins: { legend: { position: 'right', labels: { font: { size: 11 } } } } }\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t\tvar nw = document.getElementById('nw-data');\n\t\t\t\tvar nwCanvas = document.getElementById('networth-chart');\n\t\t\t\tif (nw && nwCanvas) {\n\t\t\t\t\tnew Chart(nwCanvas.getContext('2d'), {\n\t\t\t\t\t\ttype: 'line',\n\t\t\t\t\t\tdata: {\n\t\t\t\t\t\t\tlabels: JSON.parse(nw.dataset.labels),\n\t\t\t\t\t\t\tdatasets: [{\n\t\t\t\t\t\t\t\tlabel: 'Net Worth',\n\t\t\t\t\t\t\t\tdata: JSON.parse(nw.dataset.values),\n\t\t\t\t\t\t\t\tborderColor: '#b8862f',\n\t\t\t\t\t\t\t\tbackgroundColor: 'rgba(184,134,47,0.12)',\n\t\t\t\t\t\t\t\tfill: true, tension: 0.3, pointRadius: 3\n\t\t\t\t\t\t\t}]\n\t\t\t\t\t\t},\n\t\t\t\t\t\toptions: {\n\t\t\t\t\t\t\tresponsive: true,\n\t\t\t\t\t\t\tplugins: { legend: { display: false } },\n\t\t\t\t\t\t\tscales: { y: { ticks: { callback: function(v){ return 'Rp '+v.toLocaleString('id-ID'); }, font: { size: 11 } } }, x: { grid: { display: false } } }\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t})();\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
